// ============================================================
// TOPIC POOLS — Edit here to add/modify topics for exams
// ============================================================
window.TOPICS = {
accounting:["Revenue Recognition","Depreciation Methods","Inventory Valuation","Financial Statements","Cash Flow Statements","Consolidation Accounting","Lease Accounting","Foreign Currency","Intangible Assets","Provisions","Investment Property","Borrowing Costs","Related Party Disclosures","Accounting Estimates","Fair Value Measurement","Business Combinations","Employee Benefits","Financial Instruments","Share-based Payments","Segment Reporting"],
law:["Indian Contract Act","Sale of Goods Act","Partnership Act","Companies Act 2013","LLP Act","Negotiable Instruments","Consumer Protection","Arbitration Act","SEBI Regulations","Competition Act","IBC 2016","RTI Act","IT Act 2000","IP Laws","Environmental Laws","Labour Code","Industrial Relations","Social Security","Stamp Act","Registration Act"],
tax:["Income Salary","House Property","Business Profession","Capital Gains","Other Sources","Deductions 80C-80U","TDS","TCS","Advance Tax","Assessment","Appeals","Penalties","International Tax","Transfer Pricing","DTAA","GAAR","GST Levy","GST ITC","GST Registration","GST Composition"],
audit:["Audit Planning","Audit Evidence","Internal Controls","Audit Sampling","Fraud Detection","Going Concern","Company Audit","Tax Audit","GST Audit","Internal Audit","Audit Reports","Professional Ethics","Quality Control","Peer Review","CARO 2020","Audit Documentation","Substantive Procedures","Compliance Audit","Performance Audit","Forensic Audit"],
cost:["Material Costing","Labour Costing","Overhead Allocation","Process Costing","Job Costing","Contract Costing","Standard Costing","Marginal Costing","ABC Costing","Budgetary Control","Variance Analysis","CVP Analysis","Transfer Pricing","Target Costing","Life Cycle","Kaizen Costing","Throughput","Joint Products","Service Costing","Operating Costing"],
finmgmt:["Time Value Money","Capital Budgeting","Cost of Capital","Capital Structure","Working Capital","Dividend Policy","Ratio Analysis","Leverage","Portfolio Management","Derivatives Hedging","Mergers Acquisitions","Corporate Valuation","Lease vs Buy","Treasury Management","Financial Planning","Credit Analysis","Bond Valuation","Equity Valuation","Risk Return","Restructuring"],
economics:["Demand Supply","Price Elasticity","Consumer Surplus","Production Function","Cost Curves","Perfect Competition","Monopoly Oligopoly","National Income","Inflation","Monetary Policy","Fiscal Policy","Balance Payments","Trade Theory","Exchange Rates","Money Supply","Business Cycles","Public Finance","Welfare Economics","Game Theory","Behavioral Economics"],
it:["MIS","Database Management","Computer Networks","Cyber Security","Cloud Computing","ERP","Business Analytics","Blockchain","AI & ML","IT Governance COBIT","Data Privacy GDPR","SDLC","IT Audit","Digital Signatures","E-Commerce","Operating Systems","Data Warehousing","ITIL","Emerging Tech","Network Security"],
strategy:["Strategic Planning","SWOT","PESTEL","Porter Five Forces","Value Chain","Core Competencies","Corporate Strategy","Business Strategy","Balanced Scorecard","BCG Matrix","Ansoff Matrix","Blue Ocean","Corporate Governance","ERM","Change Management","Stakeholder Management","Competitive Advantage","Alliances","Diversification","Benchmarking"],
ethics:["Ethics Principles","Code of Conduct","Independence","Objectivity","Due Care","Confidentiality","Professional Behavior","Conflict Resolution","CSR","Whistleblower","Insider Trading","AML","Governance Ethics","Fiduciary Duties","Compliance","Sustainability GRI","Ethics Framework","Decision Models","Professional Scepticism","Integrity"],
fm:["Planning","Organizing","Staffing","Directing","Controlling","Leadership","Motivation Theories","Communication","Decision Making","Org Structure","HR Practices","Marketing 4Ps","Operations","TQM","Project Management","Supply Chain","Innovation","Conflict Resolution","Team Development","Corporate Culture"],
advacc:["Ind AS Framework","IFRS Convergence","Ind AS 109","Ind AS 116 Revenue","Ind AS 116 Leases","Ind AS 19","Ind AS 12","Ind AS 41","Ind AS 104","Ind AS 101","Consolidation","Ind AS 111","Ind AS 28","Ind AS 34","Ind AS 33","Ind AS 36","Post Balance Events","Policy Changes","Ind AS 113","Hyperinflation"],
corplaw:["Incorporation","MOA","AOA","Share Capital","Charges","Management","Dividends","Accounts Audit","Winding Up","NCLT NCLAT","Oppression","LLP Compliance","Producer Companies","Govt Companies","Foreign Company","Restructuring","XBRL","Board Meetings","Annual Filing","DIN DSC"],
risk:["Risk Identification","Risk Assessment","VaR","Market Risk","Credit Risk","Operational Risk","Liquidity Risk","Interest Rate Risk","FX Risk","Commodity Risk","Cyber Risk","Model Risk","Reputational Risk","Legal Risk","Systemic Risk","Mitigation","Hedging","Insurance Transfer","Risk Reporting","Basel Framework"],
quant:["Permutations","Probability","Descriptive Stats","Distributions","Hypothesis Testing","Regression","Time Series","Linear Programming","Transportation","Assignment","Game Theory","Queuing Theory","Decision Theory","Sampling","Index Numbers","Logic","Sequences","Matrices","Calculus","Financial Maths"],
invest:["Equity Markets","Bond Markets","Mutual Funds","ETF","Portfolio Theory","CAPM","APT","EMH","Technical Analysis","Fundamental Analysis","Alternative Investments","Real Estate","Private Equity","Hedge Funds","Commodity","Forex","Fixed Income","Credit Ratings","Derivatives","Investment Banking"]
};
